wheeltec_imu_node:
  ros__parameters:
    serial_port: "/dev/ttyUSB1"

nmea_serial_driver:
  ros__parameters:
    port: "/dev/ttyACM0"

motor_driver:
  ros__parameters:
    serial_port: "/dev/ttyUSB0"
    PWM_FULL: 1400
    PWM_NEUTRAL: 1500
    PWM_BRAKE: 1600
    FORWARD: 1

