/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 60.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "mjpeg"
      image_width: 1280
      image_height: 720
      camera_name: "test_camera"
      camera_info_url: "package://art_sensing_launch/config/usb_cam.params.yaml"
